#!/bin/sh

set -e

case "$1" in
    purge)
        rm -f /usr/share/keyrings/nvidia-drivers.gpg
        rm -f /etc/apt/sources.list.d/nvidia-drivers.list
        rm -f /var/cache/pni-disable-gpu
        rm -f /run/pardus-nvi.reboot
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
