#!/bin/sh

set -e 
systemctl daemon-reload | true
systemctl enable pni-disable-gpu.service | true
cat /usr/share/pardus/pardus-nvidia-installer/nvidia.pub | gpg --dearmor > /usr/share/keyrings/nvidia-drivers.gpg 
exit 0
