#!/bin/sh

set -e 
systemctl daemon-reload | true
systemctl enable pni-disable-gpu.service | true
cat /usr/share/pardus/pardus-nvidia-installer/nvidia.pub | gpg --dearmor | tee /usr/share/keyrings/nvidia-drivers.gpg > /dev/null 2>&1
exit 0
